HouseKeeping Module
fadhilrafiii/hotel-g-syariah pull request #2
Opened 2023-03-21 16:29 UTC by irfanfitriandi

2023-03-21 17:32 UTC, irfanfitriandi commented
### Dashboard
![image](https://user-images.githubusercontent.com/119382082/226692214-a26d9835-1b21-4ff5-82b2-0d471017deb9.png)

### Status HK
![image](https://user-images.githubusercontent.com/119382082/226692471-96118c26-f4a1-4c82-86b3-6eff5f4a0f7f.png)
![image](https://user-images.githubusercontent.com/119382082/226692606-58903a05-d273-4897-b009-2a3ddd1f8785.png)

### Lost Found
![image](https://user-images.githubusercontent.com/119382082/226692837-238a474d-a403-47f3-809e-76dc562cdb72.png)
![image](https://user-images.githubusercontent.com/119382082/226692964-4ec0cdf0-24f5-49ed-85ee-7341c8eabfb5.png)

### Linen
![image](https://user-images.githubusercontent.com/119382082/226693270-8788356b-45eb-4f32-b99c-b7fe0c24d4b2.png)

2023-03-23 15:49 UTC, fadhilrafiii requested changes

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/AddLinenModal/index.tsx
> +    <div>
ini isinya Modal aja yaa, buttonnya di file tempat ngimport Add Linen ini

```
const Page = () => {
   return (
      <div>
        <button>+ Tambah Linen Baru</button>
        {/* JSX lain */}
        <AddLinenModal />
      </div>
}

```

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/LostFound/AddLostFoundModal/index.tsx
> +            <select
ini diganti pke `react-select` yaaa, install dlu librarynya

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
ini jg sama yaa, isinya modal aja, buttonnya biar di tempat file yg manggil modalnya

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +        className="rounded-lg bg-blue-600 text-white px-3 py-1"
- 6px keknya rounded-md deh
- font-weigtnya 600 (semibold)
- ini paddingnya udh bener tapi kayak beda dengan figma, coba dikasih line-height: 1.25 (leading-tight)

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +            <select
ini juga ganti pke `react-select`

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +            <select
ini jg ganti pke `react-select`

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +            <select
ini jg ganti pke `react-select`

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/LinenTable/index.tsx
> +        <p className="text-sm">Showing 1 to 10 of 122 results</p>
ini paginationnya lo mau coba buat sendiri gaa, ini kan hard code. Kalo bisa implementasinya udh bener, datanya aja yg dummy

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/AddLinenModal/index.tsx
> +              className="w-full px-3 py-2 rounded-lg outline-none border-2 text-sm"
ini ganti pke `DatePicker` yaa kmaren gw udh buat coba ceek di folder component

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/LostFound/AddLostFoundModal/index.tsx
> +              type="date"
ini jga ganti pke `DatePicker` ada di components

2023-03-23 15:49 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/AddLinenModal/index.tsx
> +              type="date"
ini jg ganti pke `DatePicker` ada di components

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/LinenTable/index.tsx
> +          Edit Massal
ini iconnya jangan lupa

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/HKRoomTable/index.tsx
> +        <button className="rounded-lg bg-white text-sm border-2 py-1 px-3">
iconnya jgann lupa

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/LostFound/LostFoundTable/index.tsx
> +          Edit Massal
iconnya jgann lupa

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/HKRoomTable/index.tsx
> +      <table className="bg-white rounded-lg border-separate border border-gray-400 mx-auto my-4 w-full">
tablenya stylingnya dibenerin yaa itu ada garis 2 bawahnya

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/LostFound/LostFoundTable/index.tsx
> +      <table className="bg-white rounded-lg border-separate border border-gray-400 mx-auto my-4 w-full">
tablenya stylingnya dibenerin yaa itu ada garis 2 bawahnya

2023-03-24 01:08 UTC, fadhilrafiii commented on src/pages/HouseKeeping/Linen/LinenTable/index.tsx
> +      <table className="bg-white rounded-lg border-separate border border-gray-400 mx-auto my-4 w-full">
tablenya stylingnya dibenerin yaa itu ada garis 2 bawahnya

2023-03-25 15:24 UTC, merged