Rev hkpage
fadhilrafiii/hotel-g-syariah pull request #4
Opened 2023-04-03 16:04 UTC by irfanfitriandi

2023-04-03 16:14 UTC, irfanfitriandi commented
### Status HK

![image](https://user-images.githubusercontent.com/119382082/229567269-642a72d0-0fa5-43f8-bf8e-7c890f93a052.png)

### Lost Found

![image](https://user-images.githubusercontent.com/119382082/229567374-55c67726-c556-41ab-8fb7-e68a7299fcc4.png)

### Linen

![image](https://user-images.githubusercontent.com/119382082/229567509-29cfacd4-24bd-46d4-ba80-2f1d7354b2c1.png)

2023-04-03 16:17 UTC, irfanfitriandi commented
TODO: 
- color styling enum buat per status
- checkbox custom green color
- function => check all, sorting, searching, pagination

2023-04-04 16:41 UTC, fadhilrafiii requested changes

2023-04-04 16:41 UTC, fadhilrafiii commented on src/pages/HouseKeeping/LostFound/LostFoundTable/index.tsx
> +              const isUseArrowIcon = () => {
```
const isUseArrowIcon = data.header !== "Deskripsi" &&
                  data.header !== "Lokasi Penemuan" &&
                  data.header !== "Pemilik & No Telp";
```

2023-04-04 16:41 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +          <select
ganti pke <Select /> di components

2023-04-04 16:41 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/AddNewTaskModal/index.tsx
> +          <select
semuanyaa

2023-04-04 16:41 UTC, fadhilrafiii commented on src/pages/HouseKeeping/StatusKamar/HKRoomTable/index.tsx
> +          <input
ganti pke <Input /> semua (buat yang sama aja) klo inputnya aga beda bebas si mau pke <Input /> atau engga

2023-04-05 16:48 UTC, merged